CREATE TABLE `itens` (
  `itemID` char(6) NOT NULL,
  `dados` varchar(10000) DEFAULT NULL
);

-- INSERT INTO `itens` (`itemID`, `dados`) VALUES
-- ('asknhw', '{\"subitens\":[{\"tipo\":\"entrada-texto\",\"placeholder\":\"Definir as especificações técnicas de cada item do objeto\"}],\"entradasTexto\":[\"\"],\"nivelIndentacao\":0}'),
-- ('dujpsw', '{\"descricao\":\"Forma de adjudicação:\",\"subitens\":[{\"tipo\":\"opcao\",\"opcao\":\"Por Item.\"},{\"tipo\":\"opcao-entrada-texto\",\"opcao\":\"Por Lote. Justificativa para a formação de Lote(s): \",\"placeholderEntradaTexto\":\"Justificar tecnicamente a opção por contratação em lote(s) e o(s) critério(s) adotado(s) para a formação de cada lote\"}],\"opcao\":-1,\"entradasTexto\":[\"\",\"\"],\"nivelIndentacao\":0}'),
-- ('dxivtv', '{\"descricao\":\"Critério de julgamento das propostas:\",\"subitens\":[{\"tipo\":\"opcao\",\"opcao\":\"Menor Preço.\"},{\"tipo\":\"opcao\",\"opcao\":\"Maior Desconto.\"},{\"tipo\":\"opcao\",\"opcao\":\"Menor Taxa.\"},{\"tipo\":\"opcao\",\"opcao\":\"Maior Oferta.\"}],\"opcao\":-1,\"entradasTexto\":[\"\",\"\",\"\",\"\"],\"nivelIndentacao\":0}'),
-- ('dzdrpe', '{\"descricao\":\"Tipo de contratação:\",\"subitens\":[{\"tipo\":\"subdescricao\",\"subdescricao\":\"Fornecimento de bens/materiais:\"},{\"tipo\":\"opcao\",\"opcao\":\"Fornecimento em parcela única.\"},{\"tipo\":\"opcao\",\"opcao\":\"Fornecimento em mais de uma parcela (apresentar cronograma no item 10).\"},{\"tipo\":\"subdescricao\",\"subdescricao\":\"Prestação de serviços:\"},{\"tipo\":\"opcao\",\"opcao\":\"Prestação de serviços em regime de \\\"empreitada\\\" por preço global.\"},{\"tipo\":\"opcao\",\"opcao\":\"Prestação de serviços em regime de \\\"empreitada\\\" por preço unitário (sob demanda).\"}],\"opcao\":-1,\"entradasTexto\":[\"\",\"\",\"\",\"\",\"\",\"\"],\"nivelIndentacao\":0}'),
-- ('dzvfek', '{\"subitens\":[{\"tipo\":\"texto-fixo\",\"conteudo\":\"- Documentação comprobatória (nota fiscal, orçamento, anotação de responsabilidade técnica, etc.) que confirme ser empresa habilitada e capacitada para prestação do serviços deste Termo de Referência. O documento ou documentos devem ser apresentados no momento da contratação.\"}],\"entradasTexto\":[\"\"],\"nivelIndentacao\":1}'),
-- ('fondur', '{\"conteudo\":\"Nota: Deve ser de forma precisa, suficiente e clara, vedadas as especificações que, por excessivas, irrelevantes ou desnecessárias, limitem ou frustrem a competição, além de configurar a prática de ato antieconômico. Art. 40, I, Lei n. 8.666/93; / Art. 3º, II, Lei n. 10.520/02;\",\"nivelIndentacao\":1}'),
-- ('gxqopu', '{\"subitens\":[{\"tipo\":\"entrada-texto\",\"placeholder\":\"Detalhar a justificativa da contratação\"}],\"entradasTexto\":[\"\"],\"nivelIndentacao\":0}'),
-- ('ihxwja', '{\"descricao\":\"Caracterização do objeto:\",\"subitens\":[{\"tipo\":\"opcao\",\"opcao\":\"Bem ou serviço comum.\"},{\"tipo\":\"opcao\",\"opcao\":\"Serviço comum de engenharia.\"}],\"opcao\":-1,\"entradasTexto\":[\"\",\"\"],\"nivelIndentacao\":0}'),
-- ('obolxf', '{\"conteudo\":\"Nota: De acordo com Art. 8º, inciso I, do Decreto Estadual nº 9.666/2020, elaboração do ETP é exigida para as contratações operadas na modalidade Pregão. A princípio, não há exigência legal expressa para elaboração de ETP em contratações por outras modalidades ou para contratações diretas.\",\"nivelIndentacao\":0}'),
-- ('okxxzl', '{\"subitens\":[{\"tipo\":\"texto-fixo\",\"conteudo\":\"O fornecedor deverá apresentar:\"}],\"entradasTexto\":[\"\"],\"nivelIndentacao\":0}'),
-- ('plywcb', '{\"descricao\":\"Se prestação de serviço, é de natureza de execução continuada?\",\"subitens\":[{\"tipo\":\"opcao-entrada-texto\",\"opcao\":\"Sim. Justificar: \",\"placeholderEntradaTexto\":\"Justificativa\"},{\"tipo\":\"opcao\",\"opcao\":\"Não.\"}],\"opcao\":-1,\"entradasTexto\":[\"\",\"\"],\"nivelIndentacao\":1}'),
-- ('qodepw', '{\"subitens\":[{\"tipo\":\"texto-fixo\",\"conteudo\":\"- Prova documental que já realizou este tipo de fornecimento\"}],\"entradasTexto\":[\"\"],\"nivelIndentacao\":1}'),
-- ('qxajlk', '{\"conteudo\":\"Nota: para melhor compreensão do que sejam \\\"serviços de engenharia\\\", observar a definição e exemplos dados pela Orientação Técnica OT-IBR 002/2009-IBRAOP.\\n\\nNota: este modelo de termo de referência não deve ser utilizado para contratação de obras, ou de bens e serviços especiais nem de locações imobiliárias e alienações, porquanto estes tipos de contratação não poderão ser licitados através da modalidade de pregão (Art. 4º do Decreto nº 9.666/2020).\",\"nivelIndentacao\":1}'),
-- ('slznpt', '{\"conteudo\":\"Nota: A especificação não pode ser tão sucinta, de forma a suprimir informações ou detalhes que influenciam no valor da proposta, nem exagerada a ponto de direcionar o certame. Assim, não se pode transcrever as especificações técnicas de manuais e nem mesmo de folders/catálogos explicativos, sob pena de direcionamento do certame para determinada marca ou produto. Verificar as condições do objeto, como necessidade de instalação e montagem, incluindo ou não, o fornecimento de materiais e mão de obra. Todo material que servir de referência para a especificação do objeto deve ser juntado ao TR. Dispositivos legais: Art. 6º, IX, Lei n. 8.666/93; / Art. 7º, §2º, Lei n. 8.666/93; / Art. 15, §7º, I, Lei n. 8.666/93.\",\"nivelIndentacao\":1}'),
-- ('wfkryj', '{\"conteudo\":\"Nota: Um dos mais importantes elementos do início da contratação é a justificativa, em que minuciosamente deve o responsável pela elaboração do TR descrever a real necessidade da contratação em face do interesse público. Poderá ser apresentada a mesma justificativa constante do Estudo Técnico Preliminar, se houver. É preciso justificar o quantitativo do objeto, o que comprova a necessidade da contratação.  Dispositivos legais: Art. 15, §7º, II, Lei n. 8.666/93; Art. 3º, I, Lei n. 10.520/02.\",\"nivelIndentacao\":1}'),
-- ('zrlsuw', '{\"subitens\":[{\"tipo\":\"texto-fixo\",\"conteudo\":\"Descrição do objeto:\"},{\"tipo\":\"entrada-texto\",\"placeholder\":\"Insira aqui a descrição do objeto\",\"entradaID\":0}],\"entradasTexto\":[\"\",\"\"],\"nivelIndentacao\":0}');

ALTER TABLE `itens`
  ADD PRIMARY KEY (`itemID`);
COMMIT;
